baseURL: "https://tiangela1027.github.io/hugo-website" 
title: Angela Tian
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Writing
          url: writing/
          weight: 1
        - name: Tags
          url: tags/
          weight: 2
        - name: Archive
          url: archive/
          weight: 3

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Angela Tian
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Angela Tian ‚ú®
          subtitle: "DevOps and Cloud Engineer, 4+ years of experience. Currently working at StackAdapt. (Music producer üé∂ and avid reader üìö on the side.)"
          imageUrl: "headshot_square.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me üëã
              url: about-me
            - name: Writing ‚úèÔ∏è
              url: writing/
            - name: Spotify üéµ
              url: https://open.spotify.com/artist/2PoxTfzVLY7IXbn2a7nGdc?si=AmVEnk0rSEiZb-wbjxh39A

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Linktree
          url: https://linktr.ee/make.night
        - name: LinkedIn
          url: https://ca.linkedin.com/in/tiangela
        - name: GitHub
          url: https://github.com/tiangela1027
        - name: Credly
          url: https://www.credly.com/users/angela-t/badges#credly
        - name: Email
          url: mailto:tiangela1@gmail.com
        - name: Goodreads
          url: https://www.goodreads.com/user/show/154253154-angela

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Angela Tian"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2